### ISSUE TITLE
Assign random user name when a user opens app.

### ISSUE THREAD

**Issue by Satoshi-Sh** [Satoshi-Sh/time-tracking-application#6]
## Description
To implement the backend database, the entry needs user_id.

Please create a get_randomname function like (randomAnimal_randomNumber). Create a random name when a user opens the app and displays it next to the header. Add the user name to the df entry as well.

**Comment by radturkin** [comment]
can you assign me?

**Comment by Satoshi-Sh** [comment]
Solved on #15
